FROM almalinux:9

ENV BUILD_PLATFORM almalinux9java8

ADD almalinux9java8/gpfs.repo /etc/yum.repos.d/
ADD almalinux9java8/setup.sh almalinux9java8/settings.xml /
RUN chmod +x /setup.sh

RUN /setup.sh

ADD common/* /home/build/

RUN sh /home/build/setup-stage-area.sh && \
  mkdir /packages && chown -R build:build /packages

WORKDIR /home/build

VOLUME /m2-repository
VOLUME /packages
VOLUME /stage-area
VOLUME /stage-area-source

USER build

CMD sh -l build.sh