FROM italiangrid/pkg.base:almalinux9base

ENV BUILD_PLATFORM almalinux9java11

ADD almalinux9java11/setup.sh /
RUN chmod +x /setup.sh

RUN /setup.sh

WORKDIR /home/build

USER build

CMD sh -l build.sh