FROM  centos:centos8

ENV BUILD_PLATFORM centos8

ADD centos8/setup.sh centos8/settings.xml /
RUN chmod +x /setup.sh

RUN /setup.sh

ADD Makefile build.sh setup-stage-area.sh publish-packages.sh publish-stage-area.sh /home/build/

RUN sh /home/build/setup-stage-area.sh && \
  mkdir /packages && chown -R build:build /packages

WORKDIR /home/build

VOLUME /m2-repository
VOLUME /packages
VOLUME /stage-area
VOLUME /stage-area-source

USER build

CMD sh build.sh
