FROM  centos:centos5

ENV BUILD_PLATFORM centos5

ADD centos5/setup.sh centos5/settings.xml /
RUN chmod +x /setup.sh
ADD centos5/apache-maven.repo /etc/yum.repos.d/

RUN /setup.sh

ADD Makefile build.sh setup-stage-area.sh /home/build/

RUN sh /home/build/setup-stage-area.sh && \
  mkdir /packages && chown -R build:build /packages

WORKDIR /home/build

VOLUME /m2-repository
VOLUME /packages
VOLUME /stage-area

USER build

CMD sh build.sh
