FROM  italiangrid/build:centos7

ADD Makefile /home/build
RUN mkdir /packages && chown -R build:build /packages
WORKDIR /home/build

VOLUME /packages

ENV BUILD_PLATFORM centos7

CMD /bin/bash -l -c make
