FROM  centos:7

ENV BUILD_PLATFORM centos7base

ADD centos7base/base.sh centos7base/settings.xml /
RUN chmod +x /base.sh

ADD centos7base/apache-maven.repo centos7base/gpfs.repo centos7base/CentOS-Base.repo /etc/yum.repos.d/

RUN /base.sh

ADD common/* /home/build/

RUN sh /home/build/setup-stage-area.sh && \
  mkdir /packages && chown -R build:build /packages

VOLUME /m2-repository
VOLUME /packages
VOLUME /stage-area
VOLUME /stage-area-source