FROM  centos:7

ENV BUILD_PLATFORM centos7java17

ADD centos7java17/setup.sh centos7java17/settings.xml /
RUN chmod +x /setup.sh

ADD centos7java17/apache-maven.repo /centos7java17/gpfs.repo /etc/yum.repos.d/

RUN /setup.sh

ADD common/* /home/build/

RUN sh /home/build/setup-stage-area.sh && \
  mkdir /packages && chown -R build:build /packages

WORKDIR /home/build

VOLUME /m2-repository
VOLUME /packages
VOLUME /stage-area
VOLUME /stage-area-source

USER build

CMD sh build.sh
