FROM  italiangrid/build:centos7

ENV BUILD_PLATFORM centos7
ADD Makefile build-stage-area-repo-file.sh update-stage-area.sh /home/build/

RUN sh /home/build/build-stage-area-repo-file.sh && \
  mkdir /packages && chown -R build:build /packages && \
  mkdir -p /stage-area/$BUILD_PLATFORM && createrepo /stage-area/$BUILD_PLATFORM && \
  chown -R build:build /stage-area

WORKDIR /home/build

VOLUME /packages
VOLUME /stage-area

CMD /bin/bash -l -c make
